
CREATE TABLE ILA_COMPANY (
	ID VARCHAR(50) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	NAME VARCHAR(30),
	PRIMARY KEY (ID)
);


CREATE TABLE ILA_STAFF (
	ID VARCHAR(50) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	NAME VARCHAR(10),
	TAGS varchar(100) DEFAULT '',
	PRIMARY KEY (ID)
);


CREATE TABLE ILA_USER (
	ID VARCHAR(50) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	JOB_NUMBER VARCHAR(10) NOT NULL,
	STATUS  VARCHAR(10) NOT NULL,
    NAME VARCHAR(10) NOT NULL,
	MAIL VARCHAR(30) NOT NULL,
	PASSWORD VARCHAR(200) NOT NULL,
	SALT VARCHAR(200) NOT NULL,
	STAFF_ID VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID),
  FOREIGN KEY ( STAFF_ID ) REFERENCES ILA_STAFF ( ID )
);
CREATE TABLE ILA_ROLE (
	ID VARCHAR(50) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
    NAME VARCHAR(50) NOT NULL,
	DESCRIPTION VARCHAR(50),
	PRIMARY KEY (ID)
);

CREATE TABLE ILA_USER_ROLE (
	ROLE_ID VARCHAR(50) NOT NULL,
	USER_ID VARCHAR(50) NOT NULL,
	PRIMARY KEY (ROLE_ID, USER_ID)
);



CREATE TABLE ILA_DEPARTMENT (
	ID VARCHAR(50) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	NAME VARCHAR(50),
	PRIMARY KEY (ID)
);


CREATE TABLE ILA_ORG_ACCOUNTABILITY_TYPE (
	ID VARCHAR(50) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	DESCRIPTION VARCHAR(100),
	NAME VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE ILA_ORG_ACCOUNTABILITY (
	ID VARCHAR(50) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	CHILD_ID VARCHAR(50),
	ACCOUNTABILITY_TYPE_ID VARCHAR(50),
	PARENT_ID VARCHAR(50),
	PRIMARY KEY (ID),
	FOREIGN KEY ( ACCOUNTABILITY_TYPE_ID ) REFERENCES ILA_ORG_ACCOUNTABILITY_TYPE ( ID )
);

CREATE TABLE ILA_SOURCE (
	ID VARCHAR(50) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	NAME VARCHAR(50),
	PRIMARY KEY (ID)
);


CREATE TABLE ILA_OWNERSHIP (
	ID VARCHAR(50) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	NAME VARCHAR(50),
	PRIMARY KEY (ID)
);

CREATE TABLE ILA_SCALE (
	ID VARCHAR(50) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	NAME VARCHAR(50),
	PRIMARY KEY (ID)
);



CREATE TABLE ILA_INDUSTRY (
	ID VARCHAR(50) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	NAME VARCHAR(50),
	PRIMARY KEY (ID)
);



CREATE TABLE ILA_CLOSED_REASON (
	ID VARCHAR(50) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	NAME VARCHAR(50),
	PRIMARY KEY (ID)
);

CREATE TABLE ILA_ACTION_TYPE (
	ID VARCHAR(50) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	NAME VARCHAR(50),
	PRIMARY KEY (ID)
);

CREATE TABLE ILA_CUSTOMER (
	ID VARCHAR(50) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	DES VARCHAR(500),
	NAME VARCHAR(50),
	DEVELOP boolean NOT NULL,
	INDUSTRY_ID VARCHAR(50),
	OWNERSHIP_ID VARCHAR(50),
	SCALE_ID VARCHAR(50),
	PRIMARY KEY (ID)
);

ALTER TABLE ILA_CUSTOMER
	ADD FOREIGN KEY (INDUSTRY_ID)
	REFERENCES ILA_INDUSTRY (ID);

ALTER TABLE ILA_CUSTOMER
	ADD FOREIGN KEY (OWNERSHIP_ID)
	REFERENCES ILA_OWNERSHIP (ID);

ALTER TABLE ILA_CUSTOMER
	ADD FOREIGN KEY (SCALE_ID)
	REFERENCES ILA_SCALE (ID);


CREATE TABLE ILA_CONTACT (
	ID VARCHAR(50) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	DES VARCHAR(200),
	MAIL VARCHAR(50),
	NAME VARCHAR(50),
	TEL VARCHAR(50),
	TITLE VARCHAR(50),
	CUSTOMER_ID VARCHAR(50),
	PRIMARY KEY (ID)
);

ALTER TABLE ILA_CONTACT
	ADD FOREIGN KEY (CUSTOMER_ID)
	REFERENCES ILA_CUSTOMER (ID);

CREATE TABLE ILA_MARKET_ACTION (
	ID VARCHAR(50) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	BRIEF VARCHAR(50) NOT NULL,
	DETAIL VARCHAR(2000) NOT NULL,
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    ACTION_TYPE_ID varchar(50),
	USER_ID VARCHAR(50),
	EVENT_DATE TIMESTAMP NOT NULL,
    IMPORTANT boolean NOT NULL,
    DEPARTMENT_ID VARCHAR(50) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY ( ACTION_TYPE_ID ) REFERENCES ILA_ACTION_TYPE ( ID ),
	FOREIGN KEY ( CUSTOMER_ID ) REFERENCES ILA_CUSTOMER ( ID ),
	FOREIGN KEY ( DEPARTMENT_ID ) REFERENCES ILA_DEPARTMENT ( ID ),
	FOREIGN KEY ( USER_ID ) REFERENCES ILA_USER ( ID )
);

CREATE TABLE ILA_LEADS (
	ID VARCHAR(50) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	CLOSE_REASON_DETAIL VARCHAR(50),
	DES VARCHAR(2000),
	HIGH_AMOUNT DOUBLE NOT NULL,
	LOW_AMOUNT DOUBLE NOT NULL,
	DEAL_AMOUNT DOUBLE,
	NAME VARCHAR(100),
	OPPORTUNITY BOOLEAN NOT NULL,
	STATUS INTEGER,
	CLOSED_REASON_ID VARCHAR(50),
	CUSTOMER_ID VARCHAR(50),
	USER_ID VARCHAR(50),
	SOURCE_ID VARCHAR(50),
  DEPARTMENT_ID VARCHAR(50) NOT NULL ,
  LAST_INFO VARCHAR (200),
	PRIMARY KEY (ID),
  FOREIGN KEY ( DEPARTMENT_ID ) REFERENCES ILA_DEPARTMENT ( ID )
);

ALTER TABLE ILA_LEADS
	ADD FOREIGN KEY (CLOSED_REASON_ID)
	REFERENCES ILA_CLOSED_REASON (ID);

ALTER TABLE ILA_LEADS
	ADD FOREIGN KEY (CUSTOMER_ID)
	REFERENCES ILA_CUSTOMER (ID);

ALTER TABLE ILA_LEADS
	ADD FOREIGN KEY (SOURCE_ID)
	REFERENCES ILA_SOURCE (ID);

ALTER TABLE ILA_LEADS
	ADD FOREIGN KEY (USER_ID)
	REFERENCES ILA_USER (ID);



CREATE TABLE ILA_ACTION
(
    ID varchar(50) NOT NULL,
    CREATED_DATE timestamp NOT NULL,
    LAST_MODIFIED_DATE timestamp,
    BRIEF varchar(100),
    CUSTOMER_PARTICIPANTS varchar(100),
    DETAIL varchar(2000),
    MILESTONE boolean NOT NULL,
    OCCUR_DATE timestamp,
    SELF_PARTICIPANTS varchar(100),
    ACTION_TYPE_ID varchar(50),
    LEADS_ID varchar(50),
    USER_ID varchar(50),
    PRIMARY KEY (ID),
    FOREIGN KEY ( ACTION_TYPE_ID ) REFERENCES ILA_ACTION_TYPE ( ID ),
    FOREIGN KEY ( LEADS_ID ) REFERENCES ILA_LEADS ( ID ),
    FOREIGN KEY ( USER_ID ) REFERENCES ILA_USER ( ID )
);


CREATE TABLE ILA_DOMAIN
(
    ID varchar(50) NOT NULL,
    CREATED_DATE timestamp NOT NULL,
    LAST_MODIFIED_DATE timestamp,
    NAME varchar(50),
    DETAIL varchar(100),
    PRIMARY KEY (ID)
);

CREATE TABLE ILA_OPERATION
(
    ID varchar(50)  NOT NULL,
    CREATED_DATE timestamp NOT NULL,
    LAST_MODIFIED_DATE timestamp,
    NAME varchar(100),
    BRIEF varchar(100),
    DOMAIN_ID varchar(50) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY ( DOMAIN_ID ) REFERENCES ILA_DOMAIN ( ID )
);

CREATE TABLE ILA_PERMISSION
(
    ID varchar(50)  NOT NULL,
    CREATED_DATE timestamp NOT NULL,
    LAST_MODIFIED_DATE timestamp,
    SCOPE varchar(50) NOT NULL,
    OPERATION_ID varchar(50) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY ( OPERATION_ID ) REFERENCES ILA_OPERATION ( ID )
);


CREATE TABLE ILA_ROLE_PERMISSION(
    ROLE_ID varchar(50) NOT NULL,
    PERMISSION_ID varchar(50) NOT NULL,
    PRIMARY KEY (ROLE_ID, PERMISSION_ID)
);
