DROP ALL OBJECTS;

CREATE TABLE ILA_COMPANY (
	ID VARCHAR(255) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	NAME VARCHAR(255),
  TAGS varchar(100) DEFAULT '',
	PRIMARY KEY (ID)
);


CREATE TABLE ILA_STAFF (
	ID VARCHAR(255) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	NAME VARCHAR(255),
	TAGS varchar(100) DEFAULT '',
	PRIMARY KEY (ID)
);


CREATE TABLE ILA_USER (
	ID VARCHAR(255) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	JOB_NUMBER VARCHAR(255) NOT NULL,
	STATUS  VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
	MAIL VARCHAR(255) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	SALT VARCHAR(255) NOT NULL,
	STAFF_ID VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID),
  FOREIGN KEY ( STAFF_ID ) REFERENCES ILA_STAFF ( ID )
);
CREATE TABLE ILA_ROLE (
	ID VARCHAR(255) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
    NAME VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255),
	PRIMARY KEY (ID)
);

CREATE TABLE ILA_USER_ROLE (
	ROLE_ID VARCHAR(255) NOT NULL,
	USER_ID VARCHAR(255) NOT NULL,
	PRIMARY KEY (ROLE_ID, USER_ID)
);



CREATE TABLE ILA_DEPARTMENT (
	ID VARCHAR(255) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	NAME VARCHAR(255),
  TAGS varchar(100) DEFAULT '',
	PRIMARY KEY (ID)
);


CREATE TABLE ILA_ORG_ACCOUNTABILITY_TYPE (
	ID VARCHAR(255) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	DESCRIPTION VARCHAR(255),
	NAME VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE ILA_ORG_ACCOUNTABILITY (
	ID VARCHAR(255) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	CHILD_ID VARCHAR(255),
	ACCOUNTABILITY_TYPE_ID VARCHAR(255),
	PARENT_ID VARCHAR(255),
	PRIMARY KEY (ID)
);

ALTER TABLE ILA_ORG_ACCOUNTABILITY
	ADD FOREIGN KEY (ACCOUNTABILITY_TYPE_ID)
	REFERENCES PUBLIC.ILA_ORG_ACCOUNTABILITY_TYPE (ID);



CREATE TABLE PUBLIC.ILA_SOURCE (
	ID VARCHAR(255) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	NAME VARCHAR(255),
	PRIMARY KEY (ID)
);


CREATE TABLE PUBLIC.ILA_OWNERSHIP (
	ID VARCHAR(255) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	NAME VARCHAR(255),
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.ILA_SCALE (
	ID VARCHAR(255) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	NAME VARCHAR(255),
	PRIMARY KEY (ID)
);



CREATE TABLE PUBLIC.ILA_INDUSTRY (
	ID VARCHAR(255) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	NAME VARCHAR(255),
	PRIMARY KEY (ID)
);



CREATE TABLE PUBLIC.ILA_CLOSED_REASON (
	ID VARCHAR(255) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	NAME VARCHAR(255),
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.ILA_ACTION_TYPE (
	ID VARCHAR(255) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	NAME VARCHAR(255),
	PRIMARY KEY (ID)
);

CREATE TABLE PUBLIC.ILA_CUSTOMER (
	ID VARCHAR(255) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	DES VARCHAR(255),
	NAME VARCHAR(255),
	DEVELOP boolean NOT NULL,
	INDUSTRY_ID VARCHAR(255),
	OWNERSHIP_ID VARCHAR(255),
	SCALE_ID VARCHAR(255),
	PRIMARY KEY (ID)
);

ALTER TABLE PUBLIC.ILA_CUSTOMER
	ADD FOREIGN KEY (INDUSTRY_ID)
	REFERENCES PUBLIC.ILA_INDUSTRY (ID);

ALTER TABLE PUBLIC.ILA_CUSTOMER
	ADD FOREIGN KEY (OWNERSHIP_ID)
	REFERENCES PUBLIC.ILA_OWNERSHIP (ID);

ALTER TABLE PUBLIC.ILA_CUSTOMER
	ADD FOREIGN KEY (SCALE_ID)
	REFERENCES PUBLIC.ILA_SCALE (ID);


CREATE TABLE PUBLIC.ILA_CONTACT (
	ID VARCHAR(255) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	DES VARCHAR(255),
	MAIL VARCHAR(255),
	NAME VARCHAR(255),
	TEL VARCHAR(255),
	TITLE VARCHAR(255),
	CUSTOMER_ID VARCHAR(255),
	PRIMARY KEY (ID)
);

ALTER TABLE PUBLIC.ILA_CONTACT
	ADD FOREIGN KEY (CUSTOMER_ID)
	REFERENCES PUBLIC.ILA_CUSTOMER (ID);

CREATE TABLE PUBLIC.ILA_MARKET_ACTION (
	ID VARCHAR(255) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	BRIEF VARCHAR(255) NOT NULL,
	DETAIL VARCHAR(1000) NOT NULL,
    CUSTOMER_ID VARCHAR(255) NOT NULL,
    ACTION_TYPE_ID varchar(255),
	USER_ID VARCHAR(255),
	EVENT_DATE TIMESTAMP NOT NULL,
    IMPORTANT boolean NOT NULL,
    DEPARTMENT_ID VARCHAR(255) NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY ( ACTION_TYPE_ID ) REFERENCES ILA_ACTION_TYPE ( ID ),
	FOREIGN KEY ( CUSTOMER_ID ) REFERENCES ILA_CUSTOMER ( ID ),
	FOREIGN KEY ( DEPARTMENT_ID ) REFERENCES ILA_DEPARTMENT ( ID ),
	FOREIGN KEY ( USER_ID ) REFERENCES ILA_USER ( ID )
);

CREATE TABLE PUBLIC.ILA_LEADS (
	ID VARCHAR(255) NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	LAST_MODIFIED_DATE TIMESTAMP,
	CLOSE_REASON_DETAIL VARCHAR(255),
	DES VARCHAR(500),
	HIGH_AMOUNT DOUBLE NOT NULL,
	LOW_AMOUNT DOUBLE NOT NULL,
	DEAL_AMOUNT DOUBLE,
	NAME VARCHAR(255),
	OPPORTUNITY BOOLEAN NOT NULL,
	STATUS INTEGER,
	CLOSED_REASON_ID VARCHAR(255),
	CUSTOMER_ID VARCHAR(255),
	USER_ID VARCHAR(255),
	SOURCE_ID VARCHAR(255),
  DEPARTMENT_ID VARCHAR(255) NOT NULL ,
  LAST_INFO VARCHAR (200),
  PLAN_DEAL_DATE TIMESTAMP ,
  CLOSE_DATE TIMESTAMP,
	PRIMARY KEY (ID),
  FOREIGN KEY ( DEPARTMENT_ID ) REFERENCES ILA_DEPARTMENT ( ID )
);

ALTER TABLE PUBLIC.ILA_LEADS
	ADD FOREIGN KEY (CLOSED_REASON_ID)
	REFERENCES PUBLIC.ILA_CLOSED_REASON (ID);

ALTER TABLE PUBLIC.ILA_LEADS
	ADD FOREIGN KEY (CUSTOMER_ID)
	REFERENCES PUBLIC.ILA_CUSTOMER (ID);

ALTER TABLE PUBLIC.ILA_LEADS
	ADD FOREIGN KEY (SOURCE_ID)
	REFERENCES PUBLIC.ILA_SOURCE (ID);

ALTER TABLE PUBLIC.ILA_LEADS
	ADD FOREIGN KEY (USER_ID)
	REFERENCES PUBLIC.ILA_USER (ID);



CREATE TABLE ILA_ACTION
(
    ID varchar(255) PRIMARY KEY NOT NULL,
    CREATED_DATE timestamp NOT NULL,
    LAST_MODIFIED_DATE timestamp,
    BRIEF varchar(255),
    CUSTOMER_PARTICIPANTS varchar(255),
    DETAIL varchar(1000),
    MILESTONE boolean NOT NULL,
    OCCUR_DATE timestamp,
    SELF_PARTICIPANTS varchar(255),
    ACTION_TYPE_ID varchar(255),
    LEADS_ID varchar(255),
    USER_ID varchar(255),
    PRIMARY KEY (ID),
    FOREIGN KEY ( ACTION_TYPE_ID ) REFERENCES ILA_ACTION_TYPE ( ID ),
    FOREIGN KEY ( LEADS_ID ) REFERENCES ILA_LEADS ( ID ),
    FOREIGN KEY ( USER_ID ) REFERENCES ILA_USER ( ID )
);
CREATE INDEX FK67EFB5F7490F95F6_INDEX_2 ON ILA_ACTION ( ACTION_TYPE_ID );
CREATE INDEX FK67EFB5F763388542_INDEX_2 ON ILA_ACTION ( USER_ID );
CREATE INDEX FK67EFB5F7A32C44CB_INDEX_2 ON ILA_ACTION ( LEADS_ID );


CREATE TABLE ILA_DOMAIN
(
    ID varchar(255) PRIMARY KEY NOT NULL,
    CREATED_DATE timestamp NOT NULL,
    LAST_MODIFIED_DATE timestamp,
    NAME varchar(255),
    DETAIL varchar(255),
    PRIMARY KEY (ID),
);

CREATE TABLE ILA_OPERATION
(
    ID varchar(255) PRIMARY KEY NOT NULL,
    CREATED_DATE timestamp NOT NULL,
    LAST_MODIFIED_DATE timestamp,
    NAME varchar(255),
    BRIEF varchar(255),
    DOMAIN_ID varchar(255) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY ( DOMAIN_ID ) REFERENCES ILA_DOMAIN ( ID ),
);

CREATE TABLE ILA_PERMISSION
(
    ID varchar(255) PRIMARY KEY NOT NULL,
    CREATED_DATE timestamp NOT NULL,
    LAST_MODIFIED_DATE timestamp,
    SCOPE varchar(255) NOT NULL,
    OPERATION_ID varchar(255) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY ( OPERATION_ID ) REFERENCES ILA_OPERATION ( ID ),
);


CREATE TABLE ILA_ROLE_PERMISSION(
    ROLE_ID varchar(255) NOT NULL,
    PERMISSION_ID varchar(255) NOT NULL,
    PRIMARY KEY (ROLE_ID, PERMISSION_ID),
);
